const { GoogleSpreadsheet } = require("google-spreadsheet");

// https://docs.google.com/spreadsheets/d/1VayqQAGlFq0mNJ2HCinGzPJWUhqmrNTTajL_asWzkVs/edit#gid=0

export async function initiatlGoogleShee() {
  // Initialize the sheet - doc ID is the long id in the sheets URL
  const doc = new GoogleSpreadsheet(
    "1VayqQAGlFq0mNJ2HCinGzPJWUhqmrNTTajL_asWzkVs"
  );

  // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
  await doc.useServiceAccountAuth({
    // env var values are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    client_email: process.env.REACT_APP_GOOGLE_SERVICE_ACCOUNT_EMAIL,
    private_key: process.env.REACT_APP_GOOGLE_PRIVATE_KEY.replace(/\\n/g, "\n"),
  });

  await doc.loadInfo();

  return doc;
}

export async function getRowsFromGoogleSheet(doc) {
  // await doc.loadInfo(); // loads document properties and worksheets
  const sheet = doc.sheetsByIndex[0]; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
  return await sheet.getRows();
}
